defmodule Sensors.Reasons do
  @moduledoc """
  Lista de motivos possíveis para a detecção de um sensor.
  """
  @reasons [
    "Incêndio no convés",
    "Risco de colisão",
    "Vazamento de óleo",
    "Ataque pirata",
    "Falha no motor principal",
    "Tempestade severa se aproximando",
    "Homem ao mar",
    "Avaria no sistema de navegação",
    "Desvio de rota crítico",
    "Baixo nível de combustível",
    "Falha no rádio de comunicação",
    "Temperatura anormal da carga",
    "Queda de energia no navio",
    "Emergência médica a bordo",
    "Despressurização de compartimento",
    "Iceberg avistado",
    "Cardume de baleias na rota",
    "Presença de minas marítimas",
    "Sinal de SOS recebido",
    "Invasão de sistema cibernético",
    "Falha de hélice",
    "Entrada de água no porão",
    "Sobrecarga no gerador",
    "Perda de contato com satélite",
    "Névoa densa",
    "Bateria reserva descarregada",
    "Equipamento de segurança defeituoso",
    "Alarme de fumaça acionado",
    "Falha no controle do leme",
    "Risco de naufrágio",
    "Dano na estrutura do casco",
    "Tsunami detectado",
    "Aproximação de embarcação não identificada",
    "Ventos com força de furacão",
    "Sistema de combate a incêndio inoperante",
    "Bloqueio do canal de navegação",
    "Falha de ancoragem",
    "Corrente marítima extrema",
    "Problema com lastro",
    "Contaminação de água potável",
    "Avaria no radar",
    "Motim a bordo",
    "Falha no sonar",
    "Excesso de carga detectado",
    "Desgaste excessivo do cabo de reboque",
    "Sobrecarga nos guindastes",
    "Superaquecimento de transformador",
    "Curto-circuito no painel de controle",
    "Deslizamento de carga",
    "Falha no sistema AIS",
    "Condições de gelo extremo",
    "Incêndio na cozinha",
    "Atividade terrorista suspeita",
    "Objeto flutuante não identificado",
    "Falha no giroscópio",
    "Perda de pressão hidráulica",
    "Bomba de porão inoperante",
    "Gás tóxico detectado",
    "Bloqueio de válvulas de segurança",
    "Deslocamento no centro de gravidade",
    "Corrosão crítica identificada",
    "Perda de sinal de GPS",
    "Falha no sistema de purificação de ar",
    "Ruptura de tubulação",
    "Explosão na praça de máquinas",
    "Colisão com detritos de navio",
    "Vazamento de produto químico",
    "Anomalia térmica no reator",
    "Acionamento de alarme silencioso",
    "Falha no propulsor de proa",
    "Desconexão de cabo umbilical",
    "Nível perigoso de radiação",
    "Problema de lubrificação",
    "Falha na sonda de profundidade",
    "Obstrução de entrada de água de refrigeração",
    "Falta de resposta da tripulação",
    "Incêndio na cabine de comando",
    "Dano por impacto de ondas",
    "Vazamento no tanque de retenção",
    "Corte no cabo de internet submarino",
    "Submarino desconhecido próximo",
    "Falha de sistema pneumático",
    "Aproximação perigosa de recife",
    "Instrumentação de bordo congelada",
    "Pane no sistema de exaustão",
    "Fuga de gás refrigerante",
    "Inundação da sala de bombas",
    "Falha do piloto automático",
    "Risco de explosão por acúmulo de gás",
    "Interferência eletromagnética severa",
    "Mau funcionamento do guincho",
    "Superaquecimento de rolamentos",
    "Ruptura de vedação principal",
    "Falha no compressor de ar",
    "Incêndio em painel elétrico",
    "Risco de choque com plataforma de petróleo",
    "Queda de contêiner no mar",
    "Vazamento de combustível do tanque",
    "Fio de alta tensão exposto",
    "Colapso da antena de rádio"
  ]

  def get_random do
    Enum.random(@reasons)
  end
end
